"use client";
import { useTranslations } from "next-intl";

export const CompanyDescriptions = () => {
  const t = useTranslations("Career");

  return {
    Versa: {
      period: t("versaPeriod"),
      jobTitle: t("versaJobTitle"),
      company: "Versa",
      location: "Belo Horizonte, MG, Brazil",
      techStack: [
        "C#",
        "ASP.NET",
        "MySQL",
        "Typescript",
        "Xamarin",
        "HTML",
        "CSS",
        "GIT",
      ],
      achievements: [t("versaAchievement1"), t("versaAchievement2")],
      responsabilities: [t("versaResponsability1")],
    },

    Teknisa: {
      period: t("teknisaPeriod"),
      jobTitle: t("teknisaJobTitle"),
      company: "Teknisa",
      location: "Belo Horizonte, MG, Brazil",
      techStack: [
        "Vue.js",
        "Python",
        "Javascript",
        "Rabbit MQ",
        "HTML",
        "CSS",
        "MySQL",
        "Angular",
        "GIT",
      ],
      achievements: [t("teknisaAchievement1"), t("teknisaAchievement2")],
      responsabilities: ["Software Development", "Project Management"],
    },

    Forum: {
      period: t("forumPeriod"),
      jobTitle: t("forumJobTitle"),
      company: "Editora Forum",
      location: "Remote",
      techStack: [
        "React",
        "Redux",
        "Next.js",
        "Typescript",
        "Tailwind",
        "HTML",
        "CSS",
        "Node.js",
        "AWS",
        "GIT",
      ],
      achievements: [t("forumAchievement1"), t("forumAchievement2")],
      responsabilities: ["Software Development", "Deployment", "Design"],
    },

    Queima: {
      period: t("queimaPeriod"),
      jobTitle: t("queimaJobTitle"),
      company: "Queima Diária",
      location: "Remote",
      techStack: [
        "React",
        "React Native",
        "Styled Components",
        "Typescript",
        "HTML",
        "CSS",
        "Tizen",
        "WebOS",
        "Jest",
        "GIT",
      ],
      achievements: [
        t("queimaAchievement1"),
        t("queimaAchievement2"),
        t("queimaAchievement3"),
        t("queimaAchievement4"),
      ],
      responsabilities: [
        "Software Development",
        "Project Management",
        "Design",
        "Deployment",
        "App stores relationship",
      ],
    },

    Inter: {
      period: t("interPeriod"),
      jobTitle: t("interJobTitle"),
      company: "Banco Inter",
      location: "Remote",
      techStack: [
        "React",
        "Typescript",
        "Styled Components",
        "Postgre",
        "HTML",
        "CSS",
        "New Relic",
        "Jest",
        "AWS",
        "GIT",
      ],
      achievements: [
        t("interAchievement1"),
        t("interAchievement2"),
        t("interAchievement3"),
      ],
      responsabilities: [
        "Software Development",
        "Project Management",
        "Deployment",
      ],
    },

    Btix: {
      period: t("btixPeriod"),
      jobTitle: t("btixJobTitle"),
      company: "BTIX",
      location: "Remote",
      techStack: [
        "React",
        "Node.js",
        "React Native",
        "Next.js",
        "MongoDB",
        "Typescript",
        "CSS",
        "HTML",
        "Jest",
        "Cypress",
        "GIT",
      ],
      achievements: [
        t("btixAchievement1"),
        t("btixAchievement2"),
        t("btixAchievement3"),
      ],
      responsabilities: [
        "Software Development",
        "Project Management",
        "Team Management",
        "Deployment",
      ],
    },
    Casa: {
      period: t("casaPeriod"),
      jobTitle: t("btixJobTitle"),
      company: "Casa do Saber",
      location: "Remote",
      techStack: [
        "React",
        "React Native",
        "Styled Components",
        "Typescript",
        "CSS",
        "HTML",
        "Jest",
        "WebOS",
        "Tizen",
        "GIT",
      ],
      achievements: [t("casaAchievement1"), t("casaAchievement2")],
      responsabilities: [
        "Project Management",
        "Design",
        "Software Development",
        "Deployment",
        "App stores relationship",
      ],
    },
  };
};
