export const companyDescriptions = {
  Versa: {
    period: "jun 2019 - sep 2019",
    jobTitle: "Fullstack Intern",
    company: "Versa",
    location: "Belo Horizonte, MG, Brazil",
    techStack: [
      "Razor",
      "C#",
      "ASP.NET",
      "SQL",
      "typescript",
      "Xamarin",
      "HTML",
      "CSS",
      "GIT",
    ],
    achievements: [
      "Contributed to the translation of the code from FoxPro to ASP.NET",
      "The new project improved significantly the performance of the application",
    ],
    responsabilities: ["Software Development"],
  },
  Teknisa: {
    period: "Sep 2019 - Aug 2020",
    jobTitle: "Junior Frontend Developer",
    company: "Teknisa",
    location: "Belo Horizonte, MG, Brazil",
    techStack: [
      "Vue.js",
      "Python",
      "Javascript",
      "Rabbit MQ",
      "HTML",
      "CSS",
      "SQL",
      "Angular",
      "GIT",
    ],
    achievements: [
      "Developed a user-friendly interface for an AI project.",
      "The project was implemented in a big fast-food chain.",
    ],
    responsabilities: ["Software Development", "Project Management"],
  },
  Forum: {
    period: "Sep 2020 - Feb 2021",
    jobTitle: "Junior Frontend Developer",
    company: "Editora Forum",
    location: "Remote",
    techStack: [
      "React",
      "Redux",
      "Next.js",
      "Typescript",
      "Tailwind CSS",
      "HTML",
      "CSS",
      "Node.js",
      "AWS",
      "GIT",
    ],
    achievements: [
      "Release of a B2C online store, diversifying the company's products",
      "Through my project, the company profit increased 23%",
    ],
    responsabilities: ["Software Development", "Deployment", "Design"],
  },
  Queima: {
    period: "Mar 2021 - May 2022",
    jobTitle: "Mid-level Frontend Developer",
    company: "Queima Diária",
    location: "Remote",
    techStack: [
      "React",
      "React Native",
      "Styled Components",
      "Typescript",
      "HTML",
      "CSS",
      "Tizen",
      "WebOs",
      "Jest",
      "GIT",
    ],
    achievements: [
      "Release of the new smartTV application",
      "The project achieved a 20% increase in the number of users",
      "The project achieved a 15% increase in number of devices supported",
      "significantly redution of the deploy.",
    ],
    responsabilities: [
      "Software Development",
      "Project Management",
      "Design",
      "Deployment",
      "App stores relationship",
    ],
  },
  Inter: {
    period: "May 2022 - Apr 2023",
    jobTitle: "Mid-level Frontend Developer",
    company: "Banco Inter",
    location: "Remote",
    techStack: [
      "React",
      "Typescript",
      "Styled Components",
      "SQL",
      "HTML",
      "CSS",
      "New Relic",
      "Jest",
      "AWS",
      "GIT",
    ],
    achievements: [
      "Contributed on the internal design system release",
      "The business account onboarding app, developed by me increased the number of corporate accounts by 100%",
      "54% reduction in the number of support tickets related to corporate account opening and registration updates",
    ],
    responsabilities: [
      "Software Development",
      "Project Management",
      "Deployment",
    ],
  },

  Btix: {
    period: "Apr 2023 - Mar 2024",
    jobTitle: "Tech Lead / Senior Fullstack developer",
    company: "BTIX",
    location: "Remote",
    techStack: [
      "React",
      "Node.js",
      "React Native",
      "Next",
      "MongoDB",
      "Typescript",
      "CSS",
      "HTML",
      "Jest",
      "Cypress",
      "GIT",
    ],
    achievements: [
      "Delivery of the initial production versions of the apps",
      "Improved team synergy",
      "implementation of methodologies and practices that contribute to the quality of deliveries, such as Git Flow, for example.",
    ],
    responsabilities: [
      "Software Development",
      "Project Management",
      "Team Management",
      "Deployment",
    ],
  },
  Casa: {
    period: "Jan 2024 - Current",
    jobTitle: "Senior Frontend Developer",
    company: "Casa do Saber",
    location: "Remote",
    techStack: [
      "React",
      "React Native",
      "Styled Components",
      "Typescript",
      "CSS",
      "HTML",
      "Jest",
      "WebOS",
      "Tizen",
      "GIT",
    ],
    achievements: [
      "implemented the project from scratch",
      "Launched the first smart TV app for the company",
    ],
    responsabilities: [
      "Project Management",
      "Design",
      "Software Development",
      "Deployment",
      "App stores relationship",
    ],
  },
};
